package ui;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

//Represents FormListenerRemove (Alt + R) interface of the program
public interface FormListenerRemove {

    //EFFECTS: forms the event generated by Alt+R on keyboard
    public void formEventOccurredRemove(FormEvent e);
}
