package ui;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

//Represents FormListenerSave interface of the program
public interface FormListenerSave {

    //EFFECTS: forms the event generated by SAVE LIST JButton
    public void formEventSave(FormEvent e);
}
