package ui;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

import java.util.EventListener;

//Represents FormListenerLoad interface of the program
public interface FormListenerLoad extends EventListener {

    //EFFECTS: forms the event generated by LOAD LIST JButton on keyboard

    public void formEventLoad(FormEvent e);


}
