package ui;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

import java.util.EventListener;

//Represents FormListenerSave interface of the program
public interface FormListenerSave extends EventListener {

    //EFFECTS: forms the event generated by SAVE LIST JButton
    public void formEventSave(FormEvent e);
}
