package ui;

import java.util.EventListener;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

//Represents FormListenerAdd interface of the program
public interface FormListenerAdd extends EventListener {

    //EFFECTS: forms the event generated by Delete JButton
    public void formEventAdd(FormEvent e);

}
