package ui;

import java.util.EventListener;

//REFERENCE: the class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

//Represents interface for ListenerEnterKey (Alt + E) of the program
public interface ListenerEnterKey extends EventListener {

    //EFFECTS: forms the event generated by Alt+E on keyboard

    public void formEventOccurredEnter(FormEvent e);
}
