package ui;

import java.util.EventListener;

//REFERENCE: class codes referenced/taken from https://www.youtube.com/watch?v=WRwPVZ4jmNY&t=1211s

//Represents PanelListener interface of the program
public interface PanelListener extends EventListener {

    //EFFECTS: creates the event generated by JButtons of InteractivePanel class

    void createEvent(InteractivePanelEvent e);

}
